=== DarkPacks/SkyFactory-5/schemas/minecraft/incontrol/spawner.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "InControl Spawner",
  "description": "A list of spawner entries for InControl mod",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["conditions"],
    "properties": {
      "mob": {
        "type": ["string", "array"],
        "items": {
          "type": "string"
        }
      },
      "phase": {
        "type": ["string", "array"],
        "items": {
          "type": "string"
        }
      },
      "mobsfrombiome": {
        "type": "string",
        "enum": [
          "monster",
          "creature",
          "ambient",
          "water_creature",
          "water_ambient",
          "misc"
        ]
      },
      "attempts": {
        "type": "number"
      },
      "persecond": {
        "type": "number"
      },
      "amount": {
        "type": "object",
        "required": ["minimum", "maximum"],
        "properties": {
          "minimum": {
            "type": "number"
          },
          "maximum": {
            "type": "number"
          },
          "groupdistance": {
            "type": "number"
          }
        },
        "additionalProperties": false
      },

      "conditions": {
        "type": "object",
        "required": ["dimension"],
        "properties": {
          "dimension": {
            "type": ["string", "array"],
            "items": {
              "type": "string"
            }
          },
          "mindaycount": {
            "type": "number"
          },
          "maxdaycount": {
            "type": "number"
          },
          "mindist": {
            "type": "number"
          },
          "maxdist": {
            "type": "number"
          },
          "minheight": {
            "type": "number"
          },
          "maxheight": {
            "type": "number"
          },
          "norestrictions": {
            "type": "boolean"
          },
          "inliquid": {
            "type": "boolean"
          },
          "inwater": {
            "type": "boolean"
          },
          "inlava": {
            "type": "boolean"
          },
          "inair": {
            "type": "boolean"
          },
          "maxthis": {
            "type": "number"
          },
          "maxtotal": {
            "type": "number"
          },
          "maxpeaceful": {
            "type": "number"
          },
          "maxhostile": {
            "type": "number"
          },
          "maxneutral": {
            "type": "number"
          },
          "maxlocal": {
            "type": "number"
          },
          "validspawn": {
            "type": "boolean"
          },
          "sturdy": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  }
}

=== DarkPacks/SkyFactory-5/src/minecraft/config/incontrol/spawner.json
[
  {
    "mob": ["minecraft:zombie"],
    "persecond": 60,
    "attempts": 20,
    "amount": {
      "minimum": 4,
      "maximum": 4
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "inwater": false,
      "mindist": 16,
      "maxdist": 96,
      "maxlocal": 24
    }
  }
]
