=== DarkPacks/SkyFactory-5/schemas/minecraft/hostilenetworks/data-model.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Hostile Neural Networks Data Model",
  "description": "A Hostile Neural Networks data model datapack file",
  "type": "object",
  "properties": {
    "entity": {
      "type": "string"
    },
    "conditions": {
      "type": "array"
    },
    "variants": {
      "type": "array"
    },
    "name": {
      "type": "string"
    },
    "name_color": {
      "type": "string"
    },
    "gui_scale": {
      "type": "number"
    },
    "gui_x_offset": {
      "type": "number"
    },
    "gui_y_offset": {
      "type": "number"
    },
    "gui_z_offset": {
      "type": "number"
    },
    "sim_cost": {
      "type": "number"
    },
    "display_nbt": {
      "type": "object"
    },
    "input": {
      "$ref": "#/$defs/item"
    },
    "base_drop": {
      "$ref": "#/$defs/item"
    },
    "trivia": {
      "type": "string"
    },
    "fabricator_drops": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "type": "string"
          },
          "count": {
            "type": "number"
          },
          "optional": {
            "type": "boolean"
          }
        },
        "required": ["item"]
      }
    },
    "tier_data": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "data_per_kill": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  },
  "required": ["entity"],
  "additionalProperties": false,

  "$defs": {
    "item": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "count": {
          "type": "number"
        }
      },
      "required": ["item"]
    }
  }
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/elder_guardian.json
{
  "entity": "minecraft:elder_guardian",
  "variants": [],
  "name": "entity.minecraft.elder_guardian",
  "name_color": "#9c9d97",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 1280,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:light_gray_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.elder_guardian",
  "fabricator_drops": [
    {
      "item": "minecraft:wet_sponge",
      "count": 32
    },
    {
      "item": "minecraft:sponge",
      "count": 32
    },
    {
      "item": "minecraft:prismarine_shard",
      "count": 43
    },
    {
      "item": "minecraft:cod",
      "count": 32
    },
    {
      "item": "minecraft:prismarine_crystals",
      "count": 23
    },
    {
      "item": "minecraft:tide_armor_trim_smithing_template",
      "count": 13
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:26}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:49}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:48}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:47}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:37}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:43}",
      "optional": true
    },
    {
      "item": "sushigocrafting:shrimp",
      "count": 1,
      "nbt": "{Amount:42}",
      "optional": true
    },
    {
      "item": "minecraft:salmon",
      "count": 1
    },
    {
      "item": "sushigocrafting:raw_tuna",
      "count": 1,
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/datagen/data/minecraft/data_models/polar_bear.json
{
  "entity": "minecraft:polar_bear",
  "variants": [],
  "name": "entity.minecraft.polar_bear",
  "name_color": "#f9ffff",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:white_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.polar_bear",
  "fabricator_drops": [
    {
      "item": "minecraft:cod",
      "count": 64
    },
    {
      "item": "minecraft:salmon",
      "count": 21
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/wooly_cow.json
{
  "conditions": [
    {
      "modid": "earthmobsmod",
      "type": "forge:mod_loaded"
    }
  ],
  "entity": "earthmobsmod:wooly_cow",
  "variants": [],
  "name": "entity.earthmobsmod.wooly_cow",
  "name_color": "#f9801d",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 2560,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:orange_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.wooly_cow",
  "fabricator_drops": [
    {
      "item": "minecraft:orange_wool",
      "count": 8
    },
    {
      "item": "minecraft:beef",
      "count": 8
    },
    {
      "item": "minecraft:leather",
      "count": 8
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/energetic_sheep.json
{
  "conditions": [
    {
      "modid": "energeticsheep",
      "type": "forge:mod_loaded"
    }
  ],
  "entity": "energeticsheep:energetic_sheep",
  "variants": [],
  "name": "entity.energeticsheep.energetic_sheep",
  "name_color": "#f9ffff",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 1280,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:white_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.energetic_sheep",
  "fabricator_drops": [
    {
      "item": "energeticsheep:white_energetic_wool",
      "count": 32
    },
    {
      "item": "minecraft:mutton",
      "count": 32
    },
    {
      "item": "gateways:gate_pearl",
      "count": 32,
      "nbt": "{gateway:\"gateways:normal/energetic_sheep\"}",
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/iron_golem.json
{
  "entity": "minecraft:iron_golem",
  "variants": [],
  "name": "entity.minecraft.iron_golem",
  "name_color": "#9c9d97",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:light_gray_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.iron_golem",
  "fabricator_drops": [
    {
      "item": "minecraft:iron_ingot",
      "count": 64
    },
    {
      "item": "minecraft:poppy",
      "count": 42
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/datagen/data/minecraft/data_models/phantom.json
{
  "entity": "minecraft:phantom",
  "variants": [],
  "name": "entity.minecraft.phantom",
  "name_color": "#3c44a9",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:blue_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.phantom",
  "fabricator_drops": [
    {
      "item": "minecraft:phantom_membrane",
      "count": 64
    },
    {
      "item": "simplehats:hatbag_common",
      "count": 7,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_uncommon",
      "count": 5,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_rare",
      "count": 4,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_epic",
      "count": 2,
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/spider.json
{
  "entity": "minecraft:spider",
  "variants": [],
  "name": "entity.minecraft.spider",
  "name_color": "#1d1c21",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:black_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.spider",
  "fabricator_drops": [
    {
      "item": "minecraft:string",
      "count": 64
    },
    {
      "item": "minecraft:spider_eye",
      "count": 30
    },
    {
      "item": "simplehats:hatbag_common",
      "count": 5,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_uncommon",
      "count": 4,
      "optional": true
    },
    {
      "item": "silentgear:fine_silk",
      "count": 3,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_rare",
      "count": 2,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_epic",
      "count": 1,
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/green_chu_chu.json
{
  "conditions": [
    {
      "modid": "forcecraft",
      "type": "forge:mod_loaded"
    }
  ],
  "entity": "forcecraft:green_chu_chu",
  "variants": [],
  "name": "entity.forcecraft.green_chu_chu",
  "name_color": "#5d7c15",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:green_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.green_chu_chu",
  "fabricator_drops": [
    {
      "item": "forcecraft:green_chu_jelly",
      "count": 64
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}
