=== DarkPacks/SkyFactory-5/schemas/minecraft/hostilenetworks/data-model.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Hostile Neural Networks Data Model",
  "description": "A Hostile Neural Networks data model datapack file",
  "type": "object",
  "properties": {
    "entity": {
      "type": "string"
    },
    "conditions": {
      "type": "array"
    },
    "variants": {
      "type": "array"
    },
    "name": {
      "type": "string"
    },
    "name_color": {
      "type": "string"
    },
    "gui_scale": {
      "type": "number"
    },
    "gui_x_offset": {
      "type": "number"
    },
    "gui_y_offset": {
      "type": "number"
    },
    "gui_z_offset": {
      "type": "number"
    },
    "sim_cost": {
      "type": "number"
    },
    "display_nbt": {
      "type": "object"
    },
    "input": {
      "$ref": "#/$defs/item"
    },
    "base_drop": {
      "$ref": "#/$defs/item"
    },
    "trivia": {
      "type": "string"
    },
    "fabricator_drops": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "type": "string"
          },
          "count": {
            "type": "number"
          },
          "optional": {
            "type": "boolean"
          }
        },
        "required": ["item"]
      }
    },
    "tier_data": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "data_per_kill": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  },
  "required": ["entity"],
  "additionalProperties": false,

  "$defs": {
    "item": {
      "type": "object",
      "properties": {
        "item": {
          "type": "string"
        },
        "count": {
          "type": "number"
        }
      },
      "required": ["item"]
    }
  }
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/goat.json
{
  "conditions": [
    {
      "modid": "colourfulgoats",
      "type": "forge:mod_loaded"
    }
  ],
  "entity": "colourfulgoats:goat",
  "variants": [],
  "name": "entity.colourfulgoats.goat",
  "name_color": "#f9ffff",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 1280,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:white_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.goat",
  "fabricator_drops": [
    {
      "item": "minecraft:white_wool",
      "count": 32
    },
    {
      "item": "colourfulgoats:goat_steak",
      "count": 32
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_data/skyfactory_5/data/hostilenetworks/data_models/ghast.json
{
  "entity": "minecraft:ghast",
  "variants": [],
  "name": "entity.minecraft.ghast",
  "name_color": "#f9ffff",
  "display_nbt": {},
  "gui_scale": 0.4,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:white_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.ghast",
  "fabricator_drops": [
    {
      "item": "minecraft:gunpowder",
      "count": 64
    },
    {
      "item": "minecraft:ghast_tear",
      "count": 50
    },
    {
      "item": "simplehats:hatbag_common",
      "count": 5,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_uncommon",
      "count": 4,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_rare",
      "count": 3,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_epic",
      "count": 2,
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}

=== DarkPacks/SkyFactory-5/src/minecraft/datagen/data/minecraft/data_models/evoker.json
{
  "entity": "minecraft:evoker",
  "variants": [],
  "name": "entity.minecraft.evoker",
  "name_color": "#474f52",
  "display_nbt": {},
  "gui_scale": 1,
  "gui_x_offset": 0,
  "gui_y_offset": 0,
  "gui_z_offset": 0,
  "sim_cost": 256,
  "input": {
    "item": "hostilenetworks:prediction_matrix",
    "count": 1
  },
  "base_drop": {
    "item": "minecraft:gray_dye",
    "count": 1
  },
  "trivia": "hostilenetworks.trivia.evoker",
  "fabricator_drops": [
    {
      "item": "minecraft:totem_of_undying",
      "count": 64
    },
    {
      "item": "minecraft:emerald",
      "count": 35
    },
    {
      "item": "simplehats:hatbag_uncommon",
      "count": 3,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_common",
      "count": 3,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_rare",
      "count": 2,
      "optional": true
    },
    {
      "item": "simplehats:hatbag_epic",
      "count": 1,
      "optional": true
    }
  ],
  "tier_data": [12, 60, 360, 1260],
  "data_per_kill": [1, 4, 10, 18]
}
