=== DarkPacks/SkyFactory-5/schemas/minecraft/obscure_tooltips/style.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Obscure Tooltips Style",
  "description": "A Obscure Tooltips style datapack file",
  "type": "object",
  "properties": {
    "priority": {
      "type": "number"
    },
    "panel": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "filter": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "enchantments": {
          "type": "object"
        },
        "tags": {
          "type": "object"
        }
      }
    }
  },
  "required": ["priority", "panel", "icon", "effects", "filter"],
  "additionalProperties": false
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_resources/sf5_resources/assets/obscure_tooltips/tooltips/styles/sf5_red.json
{
  "priority": 69421,
  "panel": "obscure_tooltips:sf5_red",
  "icon": "obscure_tooltips:sf5_red",
  "effects": ["obscure_tooltips:sf5_red"],
  "filter": {
    "items": [
      "minecraft:red_dye",
      "minecraft:apple",
      "colouredstuff:sapling_red",
      "colouredstuff:planks_red",
      "colouredstuff:log_red",
      "colouredstuff:log_stripped_red",
      "colouredstuff:crafting_table_red",
      "colouredstuff:sapling_red",
      "colouredstuff:cobblestone_red",
      "colouredstuff:stone_bricks_red",
      "colouredstuff:dirt_red",
      "colouredstuff:path_red",
      "colouredstuff:farmland_red",
      "colouredstuff:smooth_sandstone_red",
      "colouredstuff:brick_red",
      "colouredstuff:chiseled_sandstone_red",
      "colouredstuff:slab_planks_red",
      "colouredstuff:slab_cobblestone_red",
      "colouredstuff:slab_stone_red",
      "colouredstuff:slab_stone_bricks_red",
      "colouredstuff:slab_sandstone_red",
      "colouredstuff:slab_brick_red",
      "colouredstuff:stairs_brick_red",
      "colouredstuff:stairs_planks_red",
      "colouredstuff:stairs_stone_red",
      "colouredstuff:stairs_cobblestone_red",
      "colouredstuff:stairs_stone_bricks_red",
      "colouredstuff:wall_stone_red",
      "colouredstuff:wall_sandstone_red",
      "colouredstuff:wall_cobblestone_red",
      "colouredstuff:wall_stone_bricks_red",
      "colouredstuff:fence_planks_red",
      "colouredstuff:gate_planks_red"
    ]
  }
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_resources/sf5_resources/assets/obscure_tooltips/tooltips/styles/sf5_white.json
{
  "priority": 69421,
  "panel": "obscure_tooltips:sf5_white",
  "icon": "obscure_tooltips:sf5_white",
  "effects": ["obscure_tooltips:sf5_white"],
  "filter": {
    "items": [
      "minecraft:white_dye",
      "sf5_things:white_apple",
      "colouredstuff:sapling_white",
      "colouredstuff:planks_white",
      "colouredstuff:log_white",
      "colouredstuff:log_stripped_white",
      "colouredstuff:crafting_table_white",
      "colouredstuff:sapling_white",
      "colouredstuff:cobblestone_white",
      "colouredstuff:stone_bricks_white",
      "colouredstuff:dirt_white",
      "colouredstuff:path_white",
      "colouredstuff:farmland_white",
      "colouredstuff:smooth_sandstone_white",
      "colouredstuff:brick_white",
      "colouredstuff:chiseled_sandstone_white",
      "colouredstuff:slab_planks_white",
      "colouredstuff:slab_cobblestone_white",
      "colouredstuff:slab_stone_white",
      "colouredstuff:slab_stone_bricks_white",
      "colouredstuff:slab_sandstone_white",
      "colouredstuff:slab_brick_white",
      "colouredstuff:stairs_brick_white",
      "colouredstuff:stairs_planks_white",
      "colouredstuff:stairs_stone_white",
      "colouredstuff:stairs_cobblestone_white",
      "colouredstuff:stairs_stone_bricks_white",
      "colouredstuff:wall_stone_white",
      "colouredstuff:wall_sandstone_white",
      "colouredstuff:wall_cobblestone_white",
      "colouredstuff:wall_stone_bricks_white",
      "colouredstuff:fence_planks_white",
      "colouredstuff:gate_planks_white"
    ]
  }
}

=== DarkPacks/SkyFactory-5/src/minecraft/global_packs/required_resources/sf5_resources/assets/obscure_tooltips/tooltips/styles/sf5_light_blue.json
{
  "priority": 69421,
  "panel": "obscure_tooltips:sf5_light_blue",
  "icon": "obscure_tooltips:sf5_light_blue",
  "effects": ["obscure_tooltips:sf5_light_blue"],
  "filter": {
    "items": [
      "ae2:light_blue_paint_ball",
      "colouredstuff:brick_light_blue",
      "colouredstuff:chiseled_sandstone_light_blue",
      "colouredstuff:chiseled_stone_bricks_light_blue",
      "colouredstuff:cobblestone_light_blue",
      "colouredstuff:crafting_table_light_blue",
      "colouredstuff:cut_sandstone_light_blue",
      "colouredstuff:dirt_light_blue",
      "colouredstuff:farmland_light_blue",
      "colouredstuff:fence_planks_light_blue",
      "colouredstuff:gate_planks_light_blue",
      "colouredstuff:leaves_light_blue",
      "colouredstuff:log_light_blue",
      "colouredstuff:log_stripped_light_blue",
      "colouredstuff:path_light_blue",
      "colouredstuff:planks_light_blue",
      "colouredstuff:sandstone_light_blue",
      "colouredstuff:sapling_light_blue",
      "colouredstuff:slab_brick_light_blue",
      "colouredstuff:slab_cobblestone_light_blue",
      "colouredstuff:slab_planks_light_blue",
      "colouredstuff:slab_sandstone_light_blue",
      "colouredstuff:slab_stone_bricks_light_blue",
      "colouredstuff:slab_stone_light_blue",
      "colouredstuff:smooth_sandstone_light_blue",
      "colouredstuff:stairs_brick_light_blue",
      "colouredstuff:stairs_cobblestone_light_blue",
      "colouredstuff:stairs_planks_light_blue",
      "colouredstuff:stairs_sandstone_light_blue",
      "colouredstuff:stairs_stone_bricks_light_blue",
      "colouredstuff:stairs_stone_light_blue",
      "colouredstuff:stone_bricks_light_blue",
      "colouredstuff:stone_light_blue",
      "colouredstuff:wall_brick_light_blue",
      "colouredstuff:wall_cobblestone_light_blue",
      "colouredstuff:wall_planks_light_blue",
      "colouredstuff:wall_sandstone_light_blue",
      "colouredstuff:wall_stone_bricks_light_blue",
      "colouredstuff:wall_stone_light_blue",
      "energeticsheep:light_blue_energetic_wool",
      "forcecraft:force_brick_light_blue",
      "forcecraft:force_brick_light_blue_slab",
      "forcecraft:force_brick_light_blue_stairs",
      "forcecraft:force_light_blue_torch",
      "forcecraft:light_blue_force_furnace",
      "minecraft:clay",
      "minecraft:clay_ball",
      "minecraft:light_blue_banner",
      "minecraft:light_blue_bed",
      "minecraft:light_blue_candle",
      "minecraft:light_blue_carpet",
      "minecraft:light_blue_concrete",
      "minecraft:light_blue_concrete_powder",
      "minecraft:light_blue_dye",
      "minecraft:light_blue_glazed_terracotta",
      "minecraft:light_blue_shulker_box",
      "minecraft:light_blue_stained_glass",
      "minecraft:light_blue_stained_glass_pane",
      "minecraft:light_blue_terracotta",
      "minecraft:light_blue_wool",
      "mysticalagriculture:light_blue_crop_essence",
      "mysticalagriculture:light_blue_crop_seeds",
      "mysticalagriculture:prosperity_block",
      "mysticalagriculture:prosperity_gemstone",
      "mysticalagriculture:prosperity_gemstone_block",
      "mysticalagriculture:prosperity_ingot",
      "mysticalagriculture:prosperity_ingot_block",
      "mysticalagriculture:prosperity_nugget",
      "mysticalagriculture:prosperity_seed_base",
      "mysticalagriculture:prosperity_shard",
      "sf5_things:light_blue_apple",
      "supplementaries:candle_holder_light_blue",
      "supplementaries:colouredstuff/sign_post_light_blue",
      "supplementaries:flag_light_blue",
      "supplementaries:present_light_blue",
      "supplementaries:trapped_present_light_blue",
      "tinted_torches:light_blue_torch",
      "minecraft:elytra",
      "sushigocrafting:raw_tuna",
      "ae2:certus_quartz_crystal",
      "minecraft:heart_of_the_sea",
      "thermal:frost_melon_slice"
    ]
  }
}
